# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes"
# My edit: "aqua" is a clean, professional skin. You can also try "air", "mint", or others.
minimal_mistakes_skin    : "aqua"

# Site Settings
locale                   : "en-US"
# My edit: Changed all the site identity fields.
title                    : "Suraj Kumar"
title_separator          : "|"
subtitle                 : "AI Researcher & PhD Student"
[cite_start]name                     : "Suraj Kumar" [cite: 1]
[cite_start]description              : "Personal website of Suraj Kumar, a Computer Science Ph.D. student at the University of Delaware specializing in Machine Learning and Natural Language Processing." [cite: 2]
# My edit: This MUST be your GitHub Pages URL.
url                      : "https://SurajK-14.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
# My edit: Point this to your repository.
[cite_start]repository               : "SurajK-14/SurajK-14.github.io" [cite: 2]
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
breadcrumbs              : true
words_per_minute         : 200

# My edit: Enabled site search, a very useful feature.
search                   : true

# SEO Related - You can add verification codes here later if you use Google/Bing Webmaster Tools
google_site_verification :
bing_site_verification   :

# Social Sharing
twitter:
  username               : # Add your twitter handle if you have one

# For specifying social profiles
social:
  type                   : Person
  [cite_start]name                   : "Suraj Kumar" [cite: 1]
  links: # An array of links to social media profiles
    - [cite_start]"https://linkedin.com/in/suraj14cs" [cite: 1]
    - [cite_start]"https://github.com/SurajK-14" [cite: 2]

# Analytics - You can set this up later if you want to track visitors
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Site Author
# My edit: This section populates the author sidebar on your posts and pages.
author:
  [cite_start]name             : "Suraj Kumar" [cite: 1]
  # My edit: You must upload a photo to this path for it to appear.
  avatar           : "/assets/images/bio-photo.jpg"
  [cite_start]bio              : "PhD Student at the University of Delaware. Focused on NLP and improving logical reasoning in LMs." [cite: 2, 4]
  location         : "Delaware / Florida"
  [cite_start]email            : "kumar@usf.edu" [cite: 1]
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      [cite_start]url: "mailto:kumar@usf.edu" [cite: 1]
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      [cite_start]url: "https://linkedin.com/in/suraj14cs" [cite: 1]
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      [cite_start]url: "https://github.com/SurajK-14" [cite: 2]
    # - label: "Google Scholar"
    #   icon: "fas fa-fw fa-graduation-cap"
    #   url: # Add your Google Scholar link here when you have one

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      [cite_start]url: "https://github.com/SurajK-14" [cite: 2]
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      [cite_start]url: "https://linkedin.com/in/suraj14cs" [cite: 1]

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# My edit: This is where you will define your collections for projects and publications.
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
